theme: jekyll-theme-cayman
title: Connor Boyle
name: Connor Boyle
email: connorboyle@sasktel.net
description: Software Developer

social-icons:
 - title: GitHub
   url: https://github.com/cjboyle
   class: github
 - title: LinkedIn
   url: https://www.linkedin.com/in/connor-boyle-557a4b153/
   class: linkedin
 - title: Twitter
   url: https://twitter.com/cjboyle_sk
   class: twitter
